name: flask_test_pipeline

on:
    push:
        branches:
            - main
            - demo

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: "Checking out"
              uses: actions/checkout@v4

            - name: "Setting up Python"
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: "Running requirements.txt"
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: "Running the Python application"
              run: |
                python app.py &
                sleep 10

            - name: "Testing the application"
              run: curl http://127.0.0.1:5000
